import Main from "@/components/Main";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import About from "@/components/About";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sajan | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/Logo.png" />
      </Head>

      <Navbar />
      <main className="flex-grow">
        <Main />
        <About />
        <Skills />
        <Projects />
        <Contact />
      </main>
      <Footer />
    </div>
  );
}